CREATE TABLE produtos (
  id SERIAL PRIMARY KEY,
  codigo VARCHAR(50) UNIQUE NOT NULL,
  nome VARCHAR(255) NOT NULL,
  descricao TEXT,
  preco NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  custo NUMERIC(12, 2),
  quantidade INTEGER NOT NULL DEFAULT 0,
  id_status int DEFAULT 1,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);